### ISSUE TITLE
Configuring LavaMusic - Using YouTube Source + LavaLink + LavaMusic

### ISSUE THREAD

**Issue by JasmeowTheCat** [appujet/lavamusic#677]
I get the following error when trying to search for a youtube video using the youtube-source plugin and LavaLink latest.

The versions are:

Youtube-source - 1.5.2
Lavalink - 4.0.7
Lavamusic - 4.6.7

I must be doing something daft - This is Lavalinks config, pretty sure I did this right:

```yml
lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.2"
      snapshot: false # Set to true if you want to use a snapshot version.
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (so the first client is queried first and so on...)
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED
```

This is the error:

```yml
Error during search: TypeError: Cannot read properties of undefined (reading 'rest')
    at Queue.search (file:///home/container/dist/structures/Queue.js:57:31)
    at InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:196:53)
    at Lavamusic.<anonymous> (file:///home/container/dist/structures/Lavamusic.js:172:60)
    at Lavamusic.emit (node:events:529:35)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/home/container/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)
    at WebSocketShard.<anonymous> (/home/container/node_modules/@discordjs/ws/dist/index.js:1190:51)
[8/12/2024] [3:21:41 AM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: TypeError: Cannot read properties of null (reading 'loadType')
    at InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:198:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error during search: TypeError: Cannot read properties of undefined (reading 'rest')
    at Queue.search (file:///home/container/dist/structures/Queue.js:57:31)
    at InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:196:53)
    at Lavamusic.<anonymous> (file:///home/container/dist/structures/Lavamusic.js:172:60)
    at Lavamusic.emit (node:events:529:35)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/home/container/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)
    at WebSocketShard.<anonymous> (/home/container/node_modules/@discordjs/ws/dist/index.js:1190:51)
[8/12/2024] [3:21:42 AM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: TypeError: Cannot read properties of null (reading 'loadType')
    at InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:198:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[8/12/2024] [3:21:57 AM] [InteractionCreate.js] [Lavamusic] › ✖  error     Error: The voice connection is not established in 15 seconds 
    at Connection.connect (file:///home/container/node_modules/shoukaku/dist/index.mjs:348:15)
    at async ShoukakuClient.joinVoiceChannel (file:///home/container/node_modules/shoukaku/dist/index.mjs:1307:7)
    at async Queue.create (file:///home/container/dist/structures/Queue.js:35:22)
    at async Play.run (file:///home/container/dist/commands/music/Play.js:51:22)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:168:17)
[8/12/2024] [3:21:57 AM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:104:46)
    at InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:188:35) {
  code: 'InteractionAlreadyReplied'
}
```
